version: '3.3'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  env_file:
  - ./.env.dev
  volumes:
  - ./app:/app
  - ./log:/app/log

 mysqldb:
  image: mysql

  ports:
    - 3306:3306

  volumes:
    - ./initdb.d:/docker-entrypoint-initdb.d


  # environment:
  # - MYSQL_ROOT_PASSWORD=p@ssw0rd1

  env_file:
  - ./.env.db

volumes:
  mysql:
  mysql_config:
